[redis]
url = "redis://127.0.0.1/"

[mainnet]
eth_rpc_http_url = "https://eth.llamarpc.com"
eth_rpc_ws_url = "wss://eth-mainnet.g.alchemy.com/v2/API-KEY"
bridge_token_factory_address = "0x252e87862A3A720287E7fd527cE6e8d0738427A2"

[testnet]
near_rpc_url = "https://rpc.testnet.near.org/"
eth_rpc_url = "https://ethereum-sepolia.blockpi.network/v1/rpc/public"
eth_chain_id = 11_155_111

token_locker_id = "omni-locker.test1-dev.testnet"
bridge_token_factory_address = "0xCF6462b9fcE5aF3E6c660c83453ECa18Ff468773"
near_light_client_eth_address = "0x202cdf10bfa45a3d2190901373edd864f071d707"
