[redis]
url = "redis://127.0.0.1/"

[near]
network = "testnet"
rpc_url = "https://rpc.testnet.near.org/"
token_locker_id = "omni-locker.testnet"
relayer_address_on_evm = "eth:0xAD167CA3A900c977d9edDf6Ec80d6095381DFD33"

[evm]
rpc_http_url = "https://eth-sepolia.g.alchemy.com/v2/API-KEY"
rpc_ws_url = "wss://eth-sepolia.g.alchemy.com/v2/API-KEY"
chain_id = 11_155_111
bridge_token_factory_address = "0xAD167CA3A900c977d9edDf6Ec80d6095381DFD33"
block_processing_batch_size = 10_000
