[redis]
url = "redis://127.0.0.1/"

[near]
network = "testnet"
rpc_url = "https://rpc.testnet.near.org/"
token_locker_id = "omni-locker.testnet"

[eth]
rpc_http_url = "https://sepolia.infura.io/v3/API_KEY"
rpc_ws_url = "wss://sepolia.infura.io/ws/v3/API_KEY"
chain_id = 11_155_111
bridge_token_factory_address = "0x3701B9859Dbb9a4333A3dd933ab18e9011ddf2C8"
light_client = "client-eth2.sepolia.testnet"
block_processing_batch_size = 10_000

[base]
rpc_http_url = "https://base-sepolia.infura.io/v3/API_KEY"
rpc_ws_url = "wss://base-sepolia.infura.io/ws/v3/API_KEY"
chain_id = 84_532
bridge_token_factory_address = "0x0C981337fFe39a555d3A40dbb32f21aD0eF33FFA"
block_processing_batch_size = 10_000

[arb]
rpc_http_url = "https://arbitrum-sepolia.infura.io/v3/API_KEY"
rpc_ws_url = "wss://arbitrum-sepolia.infura.io/ws/v3/API_KEY"
chain_id = 421_614
bridge_token_factory_address = "0xd565f7CcE0FA1bB8DBe73FCDA281390d545f6200"
block_processing_batch_size = 10_000

[solana]
rpc_http_url = "https://api.devnet.solana.com"
rpc_ws_url = "wss://api.devnet.solana.com"
program_id = "Gy1XPwYZURfBzHiGAxnw3SYC33SfqsEpGSS5zeBge28p"
wormhole_id = "3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5"
init_transfer_token_index = 6
init_transfer_emitter_index = 15
init_transfer_sol_emitter_index = 11
init_transfer_discriminator = [174, 50, 134, 99, 122, 243, 243, 224]
init_transfer_sol_discriminator = [124, 167, 164, 191, 81, 140, 108, 30]
finalize_transfer_emitter_index = 9
finalize_transfer_sol_emitter_index = 8
finalize_transfer_discriminator = [124, 126, 103, 188, 144, 65, 135, 51]
finalize_transfer_sol_discriminator = [104, 27, 121, 69, 3, 70, 217, 66]

[wormhole]
api_url = "https://api.testnet.wormholescan.io/"
solana_chain_id = 1
near_chain_id = 15
eth_chain_id = 10_002
arb_chain_id = 10_003
base_chain_id = 10_004
