[bridge_indexer]
api_url = "http://127.0.0.1:8080"

[near]
network = "mainnet"
rpc_url = "https://rpc.mainnet.near.org/"
token_locker_id = "omni.bridge.near"

[eth]
rpc_http_url = "https://mainnet.infura.io/v3/RPC_API_KEY"
rpc_ws_url = "wss://mainnet.infura.io/ws/v3/RPC_API_KEY"
chain_id = 11_155_111
bridge_token_factory_address = "0x3701B9859Dbb9a4333A3dd933ab18e9011ddf2C8"
light_client = "client-eth2.sepolia.testnet"
block_processing_batch_size = 10_000
https://wormhole.com/docs/build/reference/consistency-levels/
expected_finalization_time = 109

[base]
rpc_http_url = "https://base-mainnet.infura.io/v3/RPC_API_KEY"
rpc_ws_url = "wss://base-mainnet.infura.io/ws/v3/RPC_API_KEY"
chain_id = 8453
bridge_token_factory_address = "0xd025b38762B4A4E36F0Cde483b86CB13ea00D989"
block_processing_batch_size = 10_000
expected_finalization_time = 1026

[arb]
rpc_http_url = "https://arbitrum-mainnet.infura.io/v3/RPC_API_KEY"
rpc_ws_url = "wss://arbitrum-sepolia.infura.io/ws/v3/RPC_API_KEY"
chain_id = 42161
bridge_token_factory_address = "0xd025b38762B4A4E36F0Cde483b86CB13ea00D989"
block_processing_batch_size = 10_000
expected_finalization_time = 1066

[solana]
rpc_http_url = "https://api.mainnet-beta.solana.com"
rpc_ws_url = "wss://api.mainnet-beta.solana.com"
program_id = ""
wormhole_id = ""
init_transfer_sender_index = 0
init_transfer_token_index = 6
init_transfer_emitter_index = 15
init_transfer_sol_sender_index = 0
init_transfer_sol_emitter_index = 11
init_transfer_discriminator = [174, 50, 134, 99, 122, 243, 243, 224]
init_transfer_sol_discriminator = [124, 167, 164, 191, 81, 140, 108, 30]
finalize_transfer_emitter_index = 9
finalize_transfer_sol_emitter_index = 8
finalize_transfer_discriminator = [124, 126, 103, 188, 144, 65, 135, 51]
finalize_transfer_sol_discriminator = [104, 27, 121, 69, 3, 70, 217, 66]

[wormhole]
api_url = "https://api.wormholescan.io/"
solana_chain_id = 1
near_chain_id = 15
eth_chain_id = 2
arb_chain_id = 23
base_chain_id = 30
