[redis]
url = "redis://127.0.0.1/"
sleep_time_after_events_process_secs = 1
query_retry_attempts = 10
query_retry_sleep_secs = 1
fee_retry_base_secs = 1.2
fee_retry_max_sleep_secs = 3600 # 60 * 60
keep_transfers_for_secs = 604800 # 60 * 60 * 24 * 7

[bridge_indexer]
# Used to check if provided fee is sufficient to complete the transfer
api_url = "https://mainnet.api.bridge.nearone.org/"

mongodb_uri = "mongodb+srv://MONGODB_USERNAME:MONGODB_PASSWORD@MONGODB_HOST/?retryWrites=true&w=majority"
db_name = "mainnet_omni_bridge_db"

# Discount that relayer can accept [default: 0]
# fee_discount = 30

[near]
network = "mainnet"
rpc_url = "https://rpc.mainnet.near.org/"
omni_bridge_id = "omni.bridge.near"
btc_connector = "btc-connector.bridge.near"
btc = "btc-client.bridge.near"
# Either provide a path to a credentials file or set it in the environment
# Note: the path must be absolute
# omni_credentials_path = "/Users/username/.near-credentials/mainnet/omni-relayer.bridge.near.json"
# fast_credentials_path = "/Users/username/.near-credentials/mainnet/fast-relayer.bridge.near.json"
# We won't check fee before signing transfer if account id matches on in array
sign_without_checking_fee = ["near:aurora"]
# To enable fast relayer, uncomment the line below
# fast_relayer_enabled = true

[eth]
rpc_http_url = "https://mainnet.infura.io/v3/INFURA_API_KEY"
rpc_ws_url = "wss://mainnet.infura.io/ws/v3/INFURA_API_KEY"
chain_id = 1
omni_bridge_address = "0xe00c629aFaCCb0510995A2B95560E446A24c85B9"
light_client = "client-eth2.bridge.near"
block_processing_batch_size = 10_000
# https://wormhole.com/docs/build/reference/consistency-levels/
expected_finalization_time = 1095
safe_confirmations = 12
error_selectors_to_remove = [
	"0x8baa579f", # InvalidSignature()
	"0xdcf35db0" # FailedToSendEther()
]

[base]
rpc_http_url = "https://base-mainnet.infura.io/v3/INFURA_API_KEY"
rpc_ws_url = "wss://base-mainnet.infura.io/ws/v3/INFURA_API_KEY"
chain_id = 8453
omni_bridge_address = "0xd025b38762B4A4E36F0Cde483b86CB13ea00D989"
wormhole_address = "0xbebdb6C8ddC678FfA9f8748f85C815C556Dd8ac6"
block_processing_batch_size = 10_000
# https://wormhole.com/docs/build/reference/consistency-levels/
expected_finalization_time = 1026
safe_confirmations = 30
error_selectors_to_remove = [
	"0x8baa579f", # InvalidSignature()
	"0xdcf35db0", # FailedToSendEther()
	"696e76616c696420666565" # Wormhole's "invalid fee"
]

[arb]
rpc_http_url = "https://arbitrum-mainnet.infura.io/v3/INFURA_API_KEY"
rpc_ws_url = "wss://arbitrum-mainnet.infura.io/ws/v3/INFURA_API_KEY"
chain_id = 42_161
omni_bridge_address = "0xd025b38762B4A4E36F0Cde483b86CB13ea00D989"
wormhole_address = "0xa5f208e072434bC67592E4C49C1B991BA79BCA46"
block_processing_batch_size = 10_000
# https://wormhole.com/docs/build/reference/consistency-levels/
expected_finalization_time = 1066
safe_confirmations = 30
error_selectors_to_remove = [
	"0x8baa579f", # InvalidSignature()
	"0xdcf35db0", # FailedToSendEther()
	"696e76616c696420666565" # Wormhole's "invalid fee"
]

[bnb]
rpc_http_url = "https://bsc-mainnet.infura.io/v3/INFURA_API_KEY"
rpc_ws_url = "wss://bsc-mainnet.infura.io/ws/v3/INFURA_API_KEY"
chain_id = 56
omni_bridge_address = "0x073C8a225c8Cf9d3f9157F5C1a1DbE02407f5720"
wormhole_address = "0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B"
block_processing_batch_size = 10_000
# https://wormhole.com/docs/build/reference/consistency-levels/
expected_finalization_time = 48
safe_confirmations = 25
error_selectors_to_remove = [
	"0x8baa579f", # InvalidSignature()
	"0xdcf35db0", # FailedToSendEther()
	"696e76616c696420666565" # Wormhole's "invalid fee"
]

[solana]
rpc_http_url = "https://api.mainnet-beta.solana.com"
rpc_ws_url = "wss://api.mainnet-beta.solana.com"
# Program ID on Solana is an account ID whitch the bridge contract (basically bridge_token_factory_address on Solana)
program_id = "dahPEoZGXfyV58JqqH85okdHmpN8U2q8owgPUXSCPxe"
# This is the wormhole contract ID on Solana (can be found here https://wormhole.com/docs/build/reference/contract-addresses/#__tabbed_1_2)
wormhole_id = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"
deploy_token_emitter_index = 3
deploy_token_discriminator = [144, 104, 20, 192, 18, 112, 224, 140]
# There's a list of account keys and they are store in a strict order. We need indexes to get the right key
init_transfer_sender_index = 5
init_transfer_token_index = 1
init_transfer_emitter_index = 6
init_transfer_sol_sender_index = 1
init_transfer_sol_emitter_index = 2
# Discriminators are used to identify the type of the event (can be found during the building process of solana's contract)
init_transfer_discriminator = [174, 50, 134, 99, 122, 243, 243, 224]
init_transfer_sol_discriminator = [124, 167, 164, 191, 81, 140, 108, 30]
finalize_transfer_emitter_index = 6
finalize_transfer_sol_emitter_index = 5
finalize_transfer_discriminator = [124, 126, 103, 188, 144, 65, 135, 51]
finalize_transfer_sol_discriminator = [104, 27, 121, 69, 3, 70, 217, 66]
# Either provide a path to a keypair file or set it in the environment
# Note: the path must be absolute
# credentials_path = "/Users/username/my-solana-keypair.json"

[btc]
rpc_http_url = "https://bitcoin-rpc.publicnode.com"
# If this is set to true, then omni relayer will call `sign_btc_transaction`
signing_enabled = false
# If this is set to true, then omni relayer will call `verify_withdraw`
verifying_withdraw_enabled = false

[wormhole]
api_url = "https://api.wormholescan.io/"
solana_chain_id = 1
