name: E2E Setup
description: Setup environment for E2E tests

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Yarn
      shell: bash
      run: sudo npm install -g yarn

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.81.0
        target: wasm32-unknown-unknown

    - name: Install NEAR CLI
      shell: bash
      run: |
        cargo install --git https://github.com/Near-One/bridge-sdk-rs/ --rev 543a46a bridge-cli

    - name: Install optional additional packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Install Solana CLI and Anchor
      shell: bash
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
        export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
        cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
