[package]
name = "eth-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3", features = ["full", "node-bindings"] }

anyhow = "1.0"
futures-util = "0.3"

tokio = { version = "1", features = ["full"] }
