apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: omni-nep141-locker
  title: NEP141 Locker
  description: NEP141 Locker on Near
  tags:
    - contract
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: nearone-team
  type: contract
  lifecycle: production
  system: omnibridge-protocol
  deployedAt: []
  interactsWith: []
